# Generated by Django 2.0.3 on 2018-03-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('last_name', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('phone_number', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('email', models.EmailField(max_length=120)),
                ('role', models.CharField(choices=[('1', 'regular'), ('2', 'admin')], default='1', max_length=1)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
            },
        ),
    ]
