# Generated by Django 2.0.3 on 2018-03-16 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='University',
            new_name='Member',
        ),
        migrations.RemoveField(
            model_name='student',
            name='university',
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
